---
# 0) Cluster-wide self-signed issuer for bootstrapping the CA
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selfSigned: {}

---
# 1) Create a namespaced CA using the self-signed ClusterIssuer
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ignition-gan-ca
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  isCA: true
  commonName: ignition-gan-ca
  secretName: ignition-gan-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 17520h # 2 years
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
# 2) Namespaced Issuer that uses the CA secret created above
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ignition-gan-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ca:
    secretName: ignition-gan-ca

---
# 3) Keystore password (unchanged, but annotated so it lands early)
apiVersion: v1
kind: Secret
metadata:
  name: ignition-gan-metro-keystore
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
data:
  metro.keystore.password: bWV0cm8= # metro

---
# 4) Leaf certificate (use a valid domain!)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ignition-gan
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: ignition-gan-tls
  issuerRef:
    name: ignition-gan-issuer
    kind: Issuer
  commonName: "ignition"
  dnsNames:
    - "*.jcav.io"
  duration: 8760h # 1 year
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: ignition-gan-metro-keystore
        key: metro.keystore.password

