{{- if and .Values.enabled .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "ignition.fullname" . }}
  namespace: {{ template "ignition.namespace" . }}
  labels:
    app.kubernetes.io/component: {{ template "ignition.componentname" "" }}
{{ include "ignition.labels" . | indent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
{{ include "ignition.selectorLabels" . | indent 6 }}
{{- end }}