{{- range $i, $s := .Values.spokes }}
    {{/*
        Remember! 
        - $ refers to the root scope
        - $i is the index of the spoke we are working on
        - $s is the spoke we are working on
    */}}
    {{ $data := dict "root" $ "ingress" $.Values.ingress "context" $s }}

    {{- include "ignition.shared.ingress" $data }}
---
{{- end }}
